<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Wed Jun 17 2020 13:09:52 GMT+0000 (Coordinated Universal Time)). */
return array(
	'src/public/dist/rml_gutenberg.lite.js' => '0c71775c6cb7d47ffc17214312b22999',
	'src/public/dist/rml_gutenberg.pro.js' => '21f02d3a7643f82265040cd2750d94a6',
	'src/public/dist/rml_shortcode.lite.js' => '2b02cc89021f1b6f3e171cd323bc0245',
	'src/public/dist/rml_shortcode.pro.js' => 'd8678d0a5a464fde2fa866136e2cfdd5',
	'src/public/dist/rml.lite.js' => 'ce10e53b9f6759aa3d98a73672d26d22',
	'src/public/dist/rml.pro.js' => '4959a826740527322ffc3fa1a8f44a3b',
	'src/public/dist/rml.css' => '87f03e57ec48641c36340e94441ea6de',
);
